skinparam sequence {
  ArrowColor #5c5a5a
  ArrowFontColor #e3dddd

  LifeLineBorderColor #5c5a5a
  LifeLineBackgroundColor #1695a3

  ActorFontColor #ffffff
  ActorBorderColor #858181
  ActorBackgroundColor #ffffff
  ActorFontStyle bold

  ParticipantBorderColor #444242
  ParticipantBackgroundColor #225378
  ParticipantFontColor #ffffff
  ParticipantFontStyle bold
}

skinparam class {
	BackgroundColor #225378
	ArrowColor #5c5a5a
	ArrowFontColor #ffffff
	BorderColor #444242
  FontColor #ffffff
  AttributeFontColor #ffffff
}
